"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// import { task14A, task14B } from './lab1';
// import { Dish } from './lab2';
var createGame_1 = require("./Character/createGame");
// const a = 7.2;
// const b = 4.2;
// const xn = 1.81;
// const xk = 5.31;
// const dx = 0.7;
// const xs: number[] = [2.4, 2.8, 3.9, 4.7, 3.16];
// console.log(task14A(a, b, xn, xk, dx));
// console.log(task14B(a, b, xs));
// const dish1 = new Dish("Pizza", 15.99, "Italian");
// const dish2 = new Dish("Apple pie", 8.99, "American");
// console.log(dish1.getinfo);
// console.log(dish2.getinfo);
(0, createGame_1.createGame)();
// import { SkillFactory } from "./Character/Factories/SkillFactory";
// import { Ability } from "./Character/ability";
// import { Wizard } from "./Character/Classes/wizard";
// const testCharm = new SkillFactory();
// const charm: Ability[] = [testCharm.createAbilityFromTemplate('заворожение')];
// const testHero1 = new Wizard(100, 10, 'Biba', charm);
// const testHero2 = new Wizard(100, 10, 'Boba', charm);
// testHero1.attack(testHero2);
// testHero1.useAbility(testHero2, 'заворожение');
// console.log(testHero1);
// console.log(testHero2);
